name: DevOps Lab Exercise
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
      - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
      
      
      - run: npm ci
      - run: mpm run build --if-present
      - name: npm test    
